### ISSUE TITLE
[docker]docker compose 볼륨 갱신 안됨

### ISSUE THREAD

**Issue by vcho1958** [groom-link/groom-issue#2]
```yml
version: "3.7"
services:
  jenkins:
    build: jenkins
    container_name: "groom-jenkins"
    restart: always
    ports:
      - "4500:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/home:/var/jenkins_home --user 1000
```
이 상태일 때 컨테이너 변화가 호스트에 반영이 안돼서
고민하던 도중 컨테이너에 접속 시 계정이 jenkins인 것을 확인하여
```yml
version: "3.7"
services:
  jenkins:
    build: jenkins
    container_name: "groom-jenkins"
    restart: always
    user: jenkins
    ports:
      - "4500:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/home:/var/jenkins_home 
```
이렇게 변경하여 문제해결
